version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ".:/go/src/github.com/antonybudianto/resto-api"
      - "/go/src/github.com/antonybudianto/resto-api/vendor"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hello
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
